name: CI

on:
  pull_request:
  push:

jobs:
  unit-test:
    name: "Unit Test"
    uses: na4ma4/actions/.github/workflows/unit-test.yml@v1

  goreleaser:
    name: "Goreleaser"
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - unit-test
    uses: na4ma4/actions/.github/workflows/goreleaser.yml@v1
    secrets:
      token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
